### ISSUE TITLE
Doesn't correctly parse List of Strings

### ISSUE THREAD

**Issue by msl-kabo** [big-math-solutions/parse-dynamodb-item#2]
Hi,

Thanks for this project! However, I've found a bug :)

```js
parse({ L: [ { S: 'a-string' } ] })
// returns
[ { S: 'a-string' } ]
```

**Comment by Cereceres** [comment]
Let me check, to reproduce the bug and get fixed. 


regards

**Comment by Cereceres** [comment]
Ready, the bug is fixed, how you can see there:

https://github.com/big-math-solutions/parse-dynamodb-item/blob/8776aad18b9ea25682d4ab45d096ef5659ea98b7/test/bugs/issue1.test.js#L8

please update your version
