### ISSUE TITLE
N to be a string

### ISSUE THREAD

**Issue by dmitrirussu** [big-math-solutions/parse-dynamodb-item#3]
I have a issue when I try to dynamofy a json.... it keep numbers as number and not string

 `const result  = dynamofy({ amount: 10} );`
`//  result will be => { amount: { N: 10 } }`
// should be =>  { amount: { N: '10' } }`

**Comment by Cereceres** [comment]
The issue is resolved and UT updated to check this functionality

https://github.com/big-math-solutions/parse-dynamodb-item/blob/9f8ac3c0ce5089771d341ef25e29052a208e0ccc/test/dynamofy.test.js#L75
